//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarGenerator.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public long id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public byte[] content { get; set; }
    }
}
