//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarGenerator.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class note_text
    {
        public long id { get; set; }
        public Nullable<long> note_id { get; set; }
        public Nullable<long> language_id { get; set; }
        public string content { get; set; }
    
        public virtual language language { get; set; }
        public virtual note note { get; set; }
    }
}
